name: masar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: any
  sqflite_common_ffi_web: any
  path_provider: any
  intl: any
  flutter_local_notifications: any
  location: any
  camera: any
  google_mlkit_text_recognition: any
  shared_preferences: any
  hijri: any
  permission_handler: any
  url_launcher: any
  receive_sharing_intent: any
  dio: any
  provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
